### ISSUE TITLE
One place that supposedly has data but we’re not getting any AOIs for that location

### ISSUE THREAD

**Issue by polysteve** [3DXScape/MobileLocater#17] opened 2015-11-29 19:38 UTC

**Comment by hellokarl** [comment] 2015-11-30 02:16
57 Mott Court New London CT returns no AOIs where Brian tells us there should be 6 utilities

**Comment by polysteve** [comment] 2015-11-30 05:04
I just used the request

```
http://cbydsandbox.811central.com/ctsandbox/address:57%20mott%20ct%20new%20london%20ct/conflictcollection.json
```

and got the following six utilities. I suspect there may be some detail in the way the request is made that produces the result that you are getting

```
{
    "nonce": "",
    "results": [
        {"result": {    "activityID": "C1",     "displayName": "Eversource-CT Light & Power",   "conflictArea": "42894",    "geometry":null,    "postalCode": "06320",  "representativePoint":{"type":"Point","coordinates":[-72.095765021289381,41.30961511122652]} }},
        {"result": {    "activityID": "F5",     "displayName": "Frontier Communications",   "conflictArea": "40676",    "geometry":null,    "postalCode": "06320",  "representativePoint":{"type":"Point","coordinates":[-72.095790290848356,41.309663147118954]} }},
        {"result": {    "activityID": "OT",     "displayName": "On-Target Locating",    "conflictArea": "42894",    "geometry":null,    "postalCode": "06320",  "representativePoint":{"type":"Point","coordinates":[-72.095765021289381,41.30961511122652]} }},
        {"result": {    "activityID": "D2",     "displayName": "City of New London",    "conflictArea": "42894",    "geometry":null,    "postalCode": "06320",  "representativePoint":{"type":"Point","coordinates":[-72.095765021289381,41.30961511122652]} }},
        {"result": {    "activityID": "EE",     "displayName": "Eastern Connecticut CATV",  "conflictArea": "40676",    "geometry":null,    "postalCode": "06320",  "representativePoint":{"type":"Point","coordinates":[-72.095790290848356,41.309663147118954]} }},
        {"result": {    "activityID": "4G",     "displayName": "Eversource-Yankee Gas",     "conflictArea": "42894",    "geometry":null,    "postalCode": "06320",  "representativePoint":{"type":"Point","coordinates":[-72.095765021289381,41.30961511122652]} }}],
    "status": "OK"
}
```

**Comment by hellokarl** [comment] 2015-11-30 05:13
We’ll make this more complicated by sending you the original WKT because we don’t do it by address – it’s by wkt at that location

**Comment by polysteve** [comment] 2015-11-30 05:16
Hi Karl,

Yes, to reproduce it, we need to have the actual request info, since it presumably passed our tests. Thanks.

…steve

**Comment by hellokarl** [comment] 2015-11-30 05:17
We just repeated the exercise from OneCall and got jobs located this time.  Not sure what’s changed on whose end where, but we get authorities for it now.

We’re going to pot-hole around that area and see if we can find any other holes.

**Comment by hellokarl** [comment] 2015-12-06 23:45
If you lodge a job at 2040 Whitney ave and do not intersect the road corridor then you do not get any authorities affected.  This seems wrong and has only appeared recently.

**Comment by polysteve** [comment] 2015-12-07 03:06
Reproduced using Pelican application
Cause appears to be a reverse-geocode that finds no street according to the current algorithm.
Proposed solution is to find nearest segment in such cases because this cannot fail so algorithm is
1. use the longest street in geometry algorithm
2. if it fails, use nearest segment for street and nearest cross street for crossStreet

**Comment by 3DXScape** [comment] 2015-12-07 04:56
Reproduced.

Fixed with variable geometry for reverse geocode.

**Closed as completed by 3DXScape** 2015-12-07 04:56 UTC
